name: cart_repository
description: cart repository to manage cart database
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  cloud_firestore: ^3.1.1 
  equatable: ^2.0.3

  
dev_dependencies:
  flutter_lints: ^1.0.4