name: flowers_repository
description: Flowers repository to manage flowers database
#publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  cloud_firestore: ^3.1.1 
  equatable: ^2.0.3
  progress_timeline: ^0.0.5

  
dev_dependencies:
  flutter_lints: ^1.0.4



 
  