// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNZT0oobsQZj0ReEytNmjHzxkLolYIBM',
    appId: '1:287427916927:web:0d33fae31cfbc5f1d2fb4a',
    messagingSenderId: '287427916927',
    projectId: 'lofo-50856',
    authDomain: 'lofo-50856.firebaseapp.com',
    storageBucket: 'lofo-50856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPpFQZlm7U9R9bnHr0UB2a4T7Hh6fjM4M',
    appId: '1:287427916927:android:51a9ceec8a455d64d2fb4a',
    messagingSenderId: '287427916927',
    projectId: 'lofo-50856',
    storageBucket: 'lofo-50856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRIW-W_x13ILBfz0PlY0VzGcTP9a84tw',
    appId: '1:287427916927:ios:8e635193ad970109d2fb4a',
    messagingSenderId: '287427916927',
    projectId: 'lofo-50856',
    storageBucket: 'lofo-50856.appspot.com',
    iosClientId: '287427916927-oqvqutvp5vhpv00td9ehnucai70aabu2.apps.googleusercontent.com',
    iosBundleId: 'com.waterydesert.flowerSellingApp',
  );
}
