name: form_validators
description: A new dart package to validate forms
#publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  formz: ^0.4.0
  progress_timeline: ^0.0.5
  
dev_dependencies:
  flutter_lints: ^1.0.4
  

  
  